#!/bin/sh

case "${1}" in
  start)
    start-stop-daemon -S -p /var/run/bunnycam.pid -m -b --exec /usr/local/bin/bunnycam
    ;;

  stop)
    start-stop-daemon -K -p /var/run/bunnycam.pid
    rm -f /var/run/bunnycam.pid
    ;;

  status)
    start-stop-daemon -T -p /var/run/bunnycam.pid
    if [ $? ]; then
      echo "Stopped"
    else
      echo "Running"
    fi
    ;;

  restart)
    $0 stop
    $0 start
    ;;

  *)
    exit 1
    ;;
esac
